# Generated by Django 5.0.6 on 2024-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('content', models.TextField()),
                ('is_accepted', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_movies',
            },
        ),
    ]
