# Generated by Django 5.0.6 on 2024-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
