# Generated by Django 5.0.6 on 2024-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default=None)),
                ('roles', models.ManyToManyField(related_name='staffs', to='movie_api.role')),
            ],
        ),
    ]
