# Generated by Django 5.0.6 on 2024-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='tbl_staffs',
        ),
    ]
