# Generated by Django 5.0.6 on 2024-05-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tbl_comments',
        ),
    ]
