# Generated by Django 5.0.6 on 2024-05-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0007_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
    ]
