# Generated by Django 5.0.6 on 2024-05-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0008_alter_comment_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tbl_comments',
        ),
        migrations.AlterModelTable(
            name='role',
            table='tbl_roles',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='tbl_staffs',
        ),
    ]
