# Generated by Django 5.0.6 on 2024-05-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0009_alter_comment_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_star', models.FloatField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='movie_api.movie')),
            ],
            options={
                'db_table': 'tbl_movie_averages',
            },
        ),
    ]
